 [tool.poetry]
name = "hagent"
version = "0.1.1"
description = ""
authors = ["Farzaneh Rabiei <frabieik@ucsc.edu>" , "Jose Renau <renau@ucsc.edu>"]
readme = "README.md"

[tool.poetry.group.dev.dependencies]
pytest-cov = "^6.0.0"
ruff = "^0.8.0"

[tool.ruff]
line-length = 130

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0.2"
litellm = "^1.53.1"
diskcache = "^5.6.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore::DeprecationWarning",
   "ignore::UserWarning"
]

[tool.coverage.run]
omit = [
    "tests/*",      # Exclude the entire tests directory
    "tests/**",     # Also exclude subdirectories under tests
]
