name: Ubuntu

on: [push, pull_request]

jobs:
  install:
    name: Install Python + Poetry + HAgent package.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - name: Install project
        run: |
          poetry config virtualenvs.in-project true
          poetry lock
          poetry install
      - uses: actions/cache@v4
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
          cache-dependency-path: '**/poetry.lock'
  ruff:
    name: Run Ruff and generate a lint report
    runs-on: ubuntu-latest
    needs: install

    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/cache@v3
        name: Define a cache for the virtual environment based on the dependencies lock file
        with:
          path: ./.venv
          key: venv-${{ hashFiles('poetry.lock') }}
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
          cache-dependency-path: '**/poetry.lock'
      - name: Run ruff
        run: poetry run ruff . 
