name: Ubuntu

on: [push, pull_request]

jobs:
  install:
    name: Install Python + Poetry + HAgent package.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
          cache-dependency-path: '**/pyproject.toml'
      - name: Install project
        run: |
          poetry config virtualenvs.in-project true
          poetry lock
          poetry install
  ruff:
    name: Run Ruff and generate a lint report
    runs-on: ubuntu-latest
    needs: install

    steps:

      - uses: actions/checkout@v4
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
          cache-dependency-path: '**/pyproject.toml'
      - name: Run ruff
        run: poetry run ruff check .